### ISSUE TITLE
README needs usage examples

### ISSUE THREAD

**Issue by damien** [luisdaher/pundit_custom_errors#1]
It's not obvious what this looks like in practice and there isn't much in the way of documentation on the public API of this gem, particularly about what behaviors I should expect when I make a new class inheriting from `PunditCustomErrors::Policy`.

We should add some more documentation to the README to give everyone a better idea of the intended usage of this gem.

**Comment by luisdaher** [comment]
Good point. I don't know if `PunditCustomErrors::Policy` is necessary, though. I mean, it's cleaner to create an `exception_message` attribute inside the given `policy` class instead of extending a class. With proper documentation, it could be a cleaner approach. Duck typing ftw!

**Comment by luisdaher** [comment]
@damien could you please take a look at this?
https://github.com/luisdaher/pundit_custom_errors/blob/master/README.md

**Comment by luisdaher** [comment]
Well, as the additional documentation was added and the `PunditCustomErrors::Policy` class was removed, I'm closing this issue. @damien , thanks again for your suggestions :+1:
